services:
  - docker

before_install:
  - docker build -t mnecchi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mnecchi/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-159843085935"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  